name: campus_app
description: "Campus Guide App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  url_launcher: ^6.3.0
  http: ^1.6.0
  clarity_flutter: ^1.7.1
  flutter:
    sdk: flutter
  pointer_interceptor: ^0.10.1
  

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.0.0

  # Indoor SVG rendering
  flutter_svg: ^2.0.10
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  plugin_platform_interface: ^2.1.8

  # Google Calendar
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  syncfusion_flutter_calendar: ^32.2.9
  shared_preferences: ^2.2.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.6.3
  build_runner: ^2.4.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/indoor_svg/
    - assets/json/
    - assets/images/
    - assets/indoor_maps/geojson/Hall/
    - assets/indoor_maps/geojson/MB/
    - assets/indoor_maps/geojson/VE/
    - assets/indoor_maps/geojson/VL/ 
    - assets/indoor_maps/geojson/CC/