// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbY7I3cvhYpIhRBZKGgfCvYgZZmPBv1Y',
    appId: '1:513179995905:web:2dbe75dd54b07514a45500',
    messagingSenderId: '513179995905',
    projectId: 'campus-11a11',
    authDomain: 'campus-11a11.firebaseapp.com',
    storageBucket: 'campus-11a11.firebasestorage.app',
    measurementId: 'G-17BVH5S6LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT_le11Nu9HgExLm-FkYc_rb752yqzpNw',
    appId: '1:513179995905:android:0dc4addadb741ef7a45500',
    messagingSenderId: '513179995905',
    projectId: 'campus-11a11',
    storageBucket: 'campus-11a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTrJtf1LmmLJuDDmCbXIHlCwPzx2PSEw',
    appId: '1:513179995905:ios:03fcdacd97c14042a45500',
    messagingSenderId: '513179995905',
    projectId: 'campus-11a11',
    storageBucket: 'campus-11a11.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTrJtf1LmmLJuDDmCbXIHlCwPzx2PSEw',
    appId: '1:513179995905:ios:03fcdacd97c14042a45500',
    messagingSenderId: '513179995905',
    projectId: 'campus-11a11',
    storageBucket: 'campus-11a11.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKbY7I3cvhYpIhRBZKGgfCvYgZZmPBv1Y',
    appId: '1:513179995905:web:2e1ff09bc80f207ea45500',
    messagingSenderId: '513179995905',
    projectId: 'campus-11a11',
    authDomain: 'campus-11a11.firebaseapp.com',
    storageBucket: 'campus-11a11.firebasestorage.app',
    measurementId: 'G-05CX7G046C',
  );
}
