// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOWgUhY9TyeUW6g3jwowGgHuN549T6zs',
    appId: '1:749522791928:web:65c54adac191cd7dd2fa0d',
    messagingSenderId: '749522791928',
    projectId: 'campus-fried-chicken',
    authDomain: 'campus-fried-chicken.firebaseapp.com',
    storageBucket: 'campus-fried-chicken.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ADpfOlMu15S3gYzOrPJeeQVmQadBMFU',
    appId: '1:749522791928:android:b27afbc21b7ee80bd2fa0d',
    messagingSenderId: '749522791928',
    projectId: 'campus-fried-chicken',
    storageBucket: 'campus-fried-chicken.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtbs2jJPQjaMD9YSMT6oXkjg4YiB8mHIg',
    appId: '1:749522791928:ios:e17dd9cc1a626b5fd2fa0d',
    messagingSenderId: '749522791928',
    projectId: 'campus-fried-chicken',
    storageBucket: 'campus-fried-chicken.firebasestorage.app',
    iosBundleId: 'com.example.campusApp',
  );
}
